### ISSUE TITLE
Add automatic updates

### ISSUE THREAD

**Issue by hawkins** [hawkins/streamflow#45]
This should be fairly straightforward using [electron builder](https://github.com/electron-userland/electron-builder/wiki/Auto-Update)'s auto updater ✨

**Comment by hawkins** [comment]
I'm thinking we can use `react-toolbox`'s `Dialog` to create popups for the user to interact with the auto updater.

1. Determine if an update is available
2. Download if so
3. Open a `Dialog` when it is finished downloading, prompting the user to restart and install the app

**Comment by hawkins** [comment]
Need to be able to code sign the application, particularly for MacOS support

**Comment by hawkins** [comment]
Not actually finished yet; need to get Squirrel.Windows to work and generate a .nupkg and RELEASES file.

Currently facing issue 

```
2017-08-23 20:05:17> Program: Starting Squirrel Updater: --releasify C:\Users\hawkins\git\streamflow\dist\win\Streamflow-0.1.2-full.nupkg --releaseDir C:\Users\hawkins\git\streamflow\dist\win                                                                                                      
2017-08-23 20:05:17> Unhandled exception: System.UriFormatException: Invalid URI: The hostname could not be parsed.
at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
at System.Uri..ctor(String uriString)
at NuGet.ManifestMetadata.NuGet.IPackageMetadata.get_ProjectUrl()                                                       at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
at NuGet.ZipPackage.EnsureManifest()
at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
at Squirrel.Update.Program.ReleasifyElectron(String package, String targetDir, String baseUrl)
at Squirrel.Update.Program.executeCommandLine(String[] args)
at Squirrel.Update.Program.main(String[] args)
System.UriFormatException: Invalid URI: The hostname could not be parsed.
at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
at System.Uri..ctor(String uriString)
at NuGet.ManifestMetadata.NuGet.IPackageMetadata.get_ProjectUrl()
at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
at NuGet.ZipPackage.EnsureManifest()
at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
at Squirrel.Update.Program.ReleasifyElectron(String package, String targetDir, String baseUrl)
at Squirrel.Update.Program.executeCommandLine(String[] args)
at Squirrel.Update.Program.main(String[] args)
at Squirrel.Update.Program.Main(String[] args)
```

**Comment by hawkins** [comment]
`https://github.com/electron-userland/electron-builder/issues/2020` may have what we need

(avoiding link so as to not point to this issue from that one)

**Comment by hawkins** [comment]
In progress on #49

**Comment by hawkins** [comment]
After a lot of thought, I've decided to close this since it's taken so much time, and I frankly don't care. I'm probably the only one using this app anyways, these days, and if any users were using the app, they'd probably appreciate real updates over this hopeful one 🤔
